### PR TITLE
Fix crash when auth is enabled

### PR DESCRIPTION
**Pull request by joltcoke**
If auth is enabled and the client supplies the necessary credentials, the server will crash:

> ReferenceError: FORBIDDEN_CHARS is not defined at Object.checkUser (/opt/iobroker/node_modules/iobroker.ws/main.js:116:52) at /opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/passportSocket.js:57:28 at /opt/iobroker/node_modules/@iobroker/ws-server/index.js:188:35 at Array.forEach (<anonymous>) at Object.verifyClient (/opt/iobroker/node_modules/@iobroker/ws-server/index.js:188:21) at WebSocketServer.handleUpgrade (/opt/iobroker/node_modules/ws/lib/websocket-server.js:315:22) at Server.upgrade (/opt/iobroker/node_modules/ws/lib/websocket-server.js:112:16) at Server.emit (node:events:517:28) at Server.emit (node:domain:489:12) at onParserExecuteCommon (node:_http_server:931:14)

### CODE REVIEW

**Comment by Apollon77** [comment]
There should be the one from adapter instance used  and not defined a new?!

**Comment by joltcoke** [comment]
Any advice how to get this merged / fixed? Happy to adjust the PR, just need some more information on the general direction 😄

**Comment by Apollon77** [comment]
@joltcoke the constant should already be available on adapter level, normally adapter.FORBIDDEN_CHARS

**Comment by joltcoke** [comment]
Thanks for the hint! PR updated ✅

**Pull request merged**
